### ISSUE TITLE
Message Dashboard

### ISSUE THREAD

**Issue by kenk2** [kenk2/messenger-app#1]
# Motivation
The first step to accomplishing this app will be to be able to see a list of messages. There's quite a lot of features to think about so to start out, we should just be able to see a list of messages. 

# Tasks
- [x] Build the layout of the app.
- [x] Temporarily render in some hard-coded messages.
- [x] Build some unit tests around these messages and layouts.
