### ISSUE TITLE
Setup Message Service

### ISSUE THREAD

**Issue by kenk2** [kenk2/messenger-app#3]
# Motivation
Now that we have setup the basic layout for our app, it's time to implement the chat service. We'll use socket.io and a PostGreSQL database solution to go about implementing this. By the time this is completed, we should be able to send messages via clients to other connected clients. Finally we'll deploy this as a webapp, using ElephantSQL to do that.

# Tasks
- [x] Setup Socket.io service.
- [x] Setup PSQL service docker container.
- [x] Setup ElephantSQL managed service.
- [x] Connect Database to Socket IO.
- [x] Be able to send a message and have everyone be able to see it.
- [x] Refactor useMessage hook and message rendering to no longer use mocked data.
