### ISSUE TITLE
Extra

### ISSUE THREAD

**Issue by kenk2** [kenk2/messenger-app#5]
# Motivation
Approach when done with basic functionality...

We'd like to add a bit of icing on the cake. Several enhancement could done in order to make the app where it should be.

# Tasks
- [ ] Be able to delete/edit a message. 
- [ ] Do some re-factoring/purging of annoying ESLint rules.
- [ ] Redo some architecture to clean up messy socket interface.
