### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by kenk2** [kenk2/messenger-app#7]
# Motivation
We have the basic app running, but it still doesn't have much in the way of users. We'd like to be able to associate as someone.

# Tasks
- [x] Be able to create a user or enter as a guest.
- [x] Change up user posts so that it can be associated with an account.
- [x] Be able to see the new information as the user.
